[app]
base_url = ''

[database]
host = 'localhost'
name = 'qnuryeDotMe'
password = 'qnuryeDotMe'
port = 3306
type = 'mysql'
user = 'qnuryeDotMe'

[redis]
host = 'localhost'
idle_timeout = 200
max_active = 30
max_idle = 30
port = 6379

[secret]
client_iv = 'Kq/DrT8FzDHL0vWEROZi2w=='
client_key = 'bL0PYMvGGZdBHT82coTtM2QfYfU8z9BoMs7I7t1Jdqk='
database_iv = 'mxuEdoZ08iCGdy/X7CTFMQ=='
database_key = '0CsO4r51WkjJfmWKyw5iGm25sdF2xTzslBi/09ahBEI='
jwt = 'GtblickukA2+nqDqs2+oB8QrTPrTQMhFWIIROyBw/KI='

[server]
http_port = 8080
read_timeout = 60
run_mode = ''
write_timeout = 60
