CREATE TABLE posts (
  postId SERIAL PRIMARY KEY,
  title VARCHAR(151) NOT NULL, -- 少于 50 字
  summary VARCHAR(1801), -- 少于 600 字
  content MEDIUMTEXT NOT NULL,
  wordsCount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  viewsCount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  likesCount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updateTime TIMESTAMP ON UPDATE now(),
  uploadTime TIMESTAMP DEFAULT now()
);
